### ISSUE TITLE
Implement DH key exchange example into client <-> server architecture 

### ISSUE THREAD

**Issue by Quackster** [Quackster/ShockwaveDHKeyExchange#1]

**Comment by aromaa** [comment]
For C# implementation reference here are few classes from Skylight:

The token generation which is used for the padding decoding and the handshake: [InitDiffieHandshakePacketHandler](https://github.com/aromaa/Skylight3/blob/4787982a54e547d164fe689d9643c6cba012fa5e/src/Skylight.Server/Game/Communication/Handshake/InitDiffieHandshakePacketHandler.cs)
The handshake completion which sets the header and message crypto: [CompleteDiffieHandshakePacketHandler](https://github.com/aromaa/Skylight3/blob/4787982a54e547d164fe689d9643c6cba012fa5e/src/Skylight.Server/Game/Communication/Handshake/CompleteDiffieHandshakePacketHandler.cs)
The actual header and message parser which decodes the padding and decrypts the header and message: [Base64PacketHeaderHandler](https://github.com/aromaa/Skylight3/blob/4787982a54e547d164fe689d9643c6cba012fa5e/src/Skylight.Server/Net/Handlers/Base64PacketHeaderHandler.cs)
The RC4 implementation: [RC4](https://github.com/aromaa/Skylight3/blob/4787982a54e547d164fe689d9643c6cba012fa5e/src/Skylight.Server/Net/Crypto/RC4.cs)

**Comment by Quackster** [comment]
Thank you @aromaa 

However I already successfully did it last night: https://github.com/Quackster/Havana/commit/dcc71bfa04733de7a380cf921d997d600fe4b44e

This issue was created only to serve as a reminder to myself to commit the code here too as well as my main project. That's cool you also did this though.
